from datetime import datetime
from uuid import uuid4

import pytest
from bson import ObjectId
from mongoengine.connection import get_db

from udata.db import migrations
from udata.tests.api import PytestOnlyDBTestCase

MIGRATION = "2026-08-17-decouple-resource-id-from-ckan-remote-id.py"


def resource(resource_id, harvested=True):
    document = {"_id": resource_id, "url": "https://example.org/data.csv", "title": "data.csv"}
    if harvested:
        document["harvest"] = {"last_update": datetime(2026, 1, 1)}
    return document


def dataset(resources, backend="CKAN", archived=None, deleted=None, last_update=None):
    return {
        "_id": ObjectId(),
        # `slug` carries a unique index, so it cannot be left out of a raw insert.
        "slug": str(uuid4()),
        "resources": resources,
        "archived": archived,
        "deleted": deleted,
        "harvest": {"backend": backend, "last_update": last_update},
    }


class DecoupleResourceIdMigrationTest(PytestOnlyDBTestCase):
    @pytest.fixture
    def db(self):
        return get_db()

    @pytest.fixture
    def migrate(self, db):
        return lambda: migrations.get(MIGRATION).module.migrate(db)

    def test_harvested_resources_keep_their_id_as_remote_id(self, db, migrate):
        resource_id = str(uuid4())
        db.dataset.insert_one(dataset([resource(resource_id)]))

        migrate()

        stored = db.dataset.find_one({})["resources"][0]
        assert stored["_id"] == resource_id
        assert stored["harvest"]["remote_id"] == resource_id

    def test_manually_added_resource_gets_no_remote_id(self, db, migrate):
        """Its id was generated by udata, it never designated anything on the remote."""
        db.dataset.insert_one(dataset([resource(str(uuid4()), harvested=False)]))

        migrate()

        assert "harvest" not in db.dataset.find_one({})["resources"][0]

    def test_resources_of_other_backends_get_no_remote_id(self, db, migrate):
        """The DCAT backend correlates on the url and generates its own ids."""
        db.dataset.insert_one(dataset([resource(str(uuid4()))], backend="DCAT"))

        migrate()

        assert "remote_id" not in db.dataset.find_one({})["resources"][0]["harvest"]

    def test_live_copy_keeps_the_id(self, db, migrate):
        resource_id = str(uuid4())
        archived = dataset([resource(resource_id)], archived=datetime(2024, 9, 30))
        live = dataset([resource(resource_id)])
        db.dataset.insert_many([archived, live])

        migrate()

        assert db.dataset.find_one({"_id": live["_id"]})["resources"][0]["_id"] == resource_id
        reassigned = db.dataset.find_one({"_id": archived["_id"]})["resources"][0]
        assert reassigned["_id"] != resource_id
        # The remote id is what lets the next harvest recognize the resource it just renumbered.
        assert reassigned["harvest"]["remote_id"] == resource_id

    def test_deleted_copy_loses_the_id(self, db, migrate):
        """`get_dataset_by_resource_id` does not filter deleted datasets, so a deleted copy
        makes the id ambiguous, and it must not be the one keeping it."""
        resource_id = str(uuid4())
        deleted = dataset(
            [resource(resource_id)],
            deleted=datetime(2026, 8, 1),
            last_update=datetime(2026, 8, 17),
        )
        live = dataset([resource(resource_id)], last_update=datetime(2024, 1, 1))
        db.dataset.insert_many([deleted, live])

        migrate()

        assert db.dataset.find_one({"_id": live["_id"]})["resources"][0]["_id"] == resource_id
        assert db.dataset.find_one({"_id": deleted["_id"]})["resources"][0]["_id"] != resource_id

    def test_archived_copy_beats_a_deleted_one(self, db, migrate):
        resource_id = str(uuid4())
        deleted = dataset(
            [resource(resource_id)],
            deleted=datetime(2026, 8, 1),
            last_update=datetime(2026, 8, 17),
        )
        archived = dataset(
            [resource(resource_id)],
            archived=datetime(2024, 9, 30),
            last_update=datetime(2024, 9, 20),
        )
        db.dataset.insert_many([deleted, archived])

        migrate()

        assert db.dataset.find_one({"_id": archived["_id"]})["resources"][0]["_id"] == resource_id
        assert db.dataset.find_one({"_id": deleted["_id"]})["resources"][0]["_id"] != resource_id

    def test_every_copy_deleted_still_leaves_one_holder(self, db, migrate):
        resource_id = str(uuid4())
        older = dataset(
            [resource(resource_id)],
            deleted=datetime(2024, 1, 1),
            last_update=datetime(2023, 1, 1),
        )
        newer = dataset(
            [resource(resource_id)],
            deleted=datetime(2026, 1, 1),
            last_update=datetime(2025, 1, 1),
        )
        db.dataset.insert_many([older, newer])

        migrate()

        assert db.dataset.find_one({"_id": newer["_id"]})["resources"][0]["_id"] == resource_id
        assert db.dataset.find_one({"_id": older["_id"]})["resources"][0]["_id"] != resource_id

    def test_most_recently_harvested_copy_wins_between_live_ones(self, db, migrate):
        """A dataset can stay unarchived after its harvest flagged it `not-on-remote`."""
        resource_id = str(uuid4())
        stale = dataset([resource(resource_id)], last_update=datetime(2024, 9, 20))
        current = dataset([resource(resource_id)], last_update=datetime(2026, 8, 17))
        db.dataset.insert_many([stale, current])

        migrate()

        assert db.dataset.find_one({"_id": current["_id"]})["resources"][0]["_id"] == resource_id
        assert db.dataset.find_one({"_id": stale["_id"]})["resources"][0]["_id"] != resource_id

    def test_every_copy_archived_still_leaves_one_holder(self, db, migrate):
        resource_id = str(uuid4())
        older = dataset(
            [resource(resource_id)],
            archived=datetime(2022, 9, 28),
            last_update=datetime(2022, 9, 20),
        )
        newer = dataset(
            [resource(resource_id)],
            archived=datetime(2024, 9, 30),
            last_update=datetime(2024, 9, 20),
        )
        db.dataset.insert_many([older, newer])

        migrate()

        assert db.dataset.find_one({"_id": newer["_id"]})["resources"][0]["_id"] == resource_id
        assert db.dataset.find_one({"_id": older["_id"]})["resources"][0]["_id"] != resource_id

    def test_rerunning_the_migration_changes_nothing(self, db, migrate):
        resource_id = str(uuid4())
        archived = dataset([resource(resource_id)], archived=datetime(2024, 9, 30))
        live = dataset([resource(resource_id)])
        db.dataset.insert_many([archived, live])

        migrate()
        after_first_run = {d["_id"]: d["resources"][0] for d in db.dataset.find({})}
        migrate()

        assert {d["_id"]: d["resources"][0] for d in db.dataset.find({})} == after_first_run

    def test_unique_resources_are_left_alone(self, db, migrate):
        first, second = str(uuid4()), str(uuid4())
        db.dataset.insert_many([dataset([resource(first)]), dataset([resource(second)])])

        migrate()

        assert {d["resources"][0]["_id"] for d in db.dataset.find({})} == {first, second}

    def test_the_same_id_in_several_datasets_is_resolved(self, db, migrate):
        """The shape the CKAN backend used to produce: one live dataset and its archived
        generations, all holding the same resource ids."""
        resource_id = str(uuid4())
        generations = [
            dataset([resource(resource_id)], archived=datetime(2024, 1, 1)) for _ in range(3)
        ]
        live = dataset([resource(resource_id)])
        db.dataset.insert_many(generations + [live])

        migrate()

        ids = [d["resources"][0]["_id"] for d in db.dataset.find({})]
        assert len(set(ids)) == 4
        assert db.dataset.find_one({"_id": live["_id"]})["resources"][0]["_id"] == resource_id
