from datetime import datetime
from uuid import uuid4

import pytest
from mongoengine.connection import get_db

from udata.core.dataset.factories import DatasetFactory, ResourceFactory
from udata.core.dataset.models import (
    Dataset,
    HarvestDatasetMetadata,
    HarvestResourceMetadata,
)
from udata.db import migrations
from udata.harvest.tests.factories import HarvestSourceFactory
from udata.tests.api import PytestOnlyDBTestCase

MIGRATION = "2026-08-17-decouple-resource-id-from-ckan-remote-id.py"


def resource(resource_id=None, harvested=True, **kwargs):
    harvest = HarvestResourceMetadata(last_update=datetime(2026, 1, 1)) if harvested else None
    return ResourceFactory(id=resource_id or str(uuid4()), harvest=harvest, **kwargs)


def dataset(resources, backend="CKAN", source_id=None, last_update=None, **kwargs):
    harvest = HarvestDatasetMetadata(backend=backend, source_id=source_id, last_update=last_update)
    return DatasetFactory(resources=resources, harvest=harvest, **kwargs)


def resources_of(dataset):
    return Dataset.objects.get(id=dataset.id).resources


def migrate():
    migrations.get(MIGRATION).migrate(get_db())


@pytest.mark.options(HARVESTER_BACKENDS=["ckan", "dkan"])
class DecoupleResourceIdMigrationTest(PytestOnlyDBTestCase):
    def test_harvested_resources_keep_their_id_as_remote_id(self):
        resource_id = str(uuid4())
        harvested = dataset([resource(resource_id)])

        migrate()

        stored = resources_of(harvested)[0]
        assert str(stored.id) == resource_id
        assert stored.harvest.remote_id == resource_id

    def test_manually_added_resource_gets_no_remote_id(self):
        """Its id was generated by udata, it never designated anything on the remote."""
        harvested = dataset([resource(harvested=False)])

        migrate()

        assert resources_of(harvested)[0].harvest is None

    def test_dkan_resources_keep_their_id_as_remote_id(self):
        """`DkanBackend` inherits `inner_process_dataset`, so it adopted remote ids too."""
        resource_id = str(uuid4())
        source = HarvestSourceFactory(backend="dkan")
        harvested = dataset([resource(resource_id)], backend=None, source_id=str(source.id))

        migrate()

        assert Dataset.objects.get(id=harvested.id).harvest.backend == "DKAN"
        assert resources_of(harvested)[0].harvest.remote_id == resource_id

    def test_resources_of_other_backends_get_no_remote_id(self):
        """The DCAT backend correlates on the url and generates its own ids."""
        harvested = dataset([resource()], backend="DCAT")

        migrate()

        assert resources_of(harvested)[0].harvest.remote_id is None

    def test_backend_is_taken_from_the_source(self):
        """No migration ever filled `harvest.backend`, so it is missing wherever a source
        stopped running before the field existed."""
        source = HarvestSourceFactory(backend="ckan")
        harvested = dataset([resource()], backend=None, source_id=str(source.id))

        migrate()

        assert Dataset.objects.get(id=harvested.id).harvest.backend == "CKAN"

    def test_a_backfilled_backend_widens_the_remote_id_backfill(self):
        """Which is why the backend comes first: the remote id backfill selects on it."""
        source = HarvestSourceFactory(backend="ckan")
        resource_id = str(uuid4())
        harvested = dataset([resource(resource_id)], backend=None, source_id=str(source.id))

        migrate()

        assert resources_of(harvested)[0].harvest.remote_id == resource_id

    def test_other_resources_of_the_dataset_are_left_untouched(self):
        """The backfill rewrites the whole `resources` array and the deduplication addresses
        one element by position: neither may disturb the siblings."""
        shared_id, own_id = str(uuid4()), str(uuid4())
        manual = resource(harvested=False, title="added by hand")
        harvested = dataset([resource(shared_id), manual, resource(own_id)])
        dataset([resource(shared_id)], archived=datetime(2024, 9, 30))

        migrate()

        first, second, third = resources_of(harvested)
        assert str(first.id) == shared_id
        assert first.harvest.remote_id == shared_id
        assert second.title == "added by hand"
        assert second.harvest is None
        assert str(third.id) == own_id
        assert third.harvest.remote_id == own_id

    def test_live_copy_keeps_the_id(self):
        resource_id = str(uuid4())
        # The archived copy is the most recently harvested one: being live has to win anyway.
        archived = dataset(
            [resource(resource_id)],
            archived=datetime(2024, 9, 30),
            last_update=datetime(2026, 8, 17),
        )
        live = dataset([resource(resource_id)], last_update=datetime(2024, 1, 1))

        migrate()

        assert str(resources_of(live)[0].id) == resource_id
        reassigned = resources_of(archived)[0]
        assert str(reassigned.id) != resource_id
        # The remote id is what lets the next harvest recognize the resource it just renumbered.
        assert reassigned.harvest.remote_id == resource_id

    def test_deleted_copy_loses_the_id(self):
        """`get_dataset_by_resource_id` does not filter deleted datasets, so a deleted copy
        makes the id ambiguous, and it must not be the one keeping it."""
        resource_id = str(uuid4())
        deleted = dataset(
            [resource(resource_id)],
            deleted=datetime(2026, 8, 1),
            last_update=datetime(2026, 8, 17),
        )
        live = dataset([resource(resource_id)], last_update=datetime(2024, 1, 1))

        migrate()

        assert str(resources_of(live)[0].id) == resource_id
        assert str(resources_of(deleted)[0].id) != resource_id

    def test_archived_copy_beats_a_deleted_one(self):
        resource_id = str(uuid4())
        deleted = dataset(
            [resource(resource_id)],
            deleted=datetime(2026, 8, 1),
            last_update=datetime(2026, 8, 17),
        )
        archived = dataset(
            [resource(resource_id)],
            archived=datetime(2024, 9, 30),
            last_update=datetime(2024, 9, 20),
        )

        migrate()

        assert str(resources_of(archived)[0].id) == resource_id
        assert str(resources_of(deleted)[0].id) != resource_id

    def test_every_copy_deleted_still_leaves_one_holder(self):
        resource_id = str(uuid4())
        older = dataset(
            [resource(resource_id)],
            deleted=datetime(2024, 1, 1),
            last_update=datetime(2023, 1, 1),
        )
        newer = dataset(
            [resource(resource_id)],
            deleted=datetime(2026, 1, 1),
            last_update=datetime(2025, 1, 1),
        )

        migrate()

        assert str(resources_of(newer)[0].id) == resource_id
        assert str(resources_of(older)[0].id) != resource_id

    def test_most_recently_harvested_copy_wins_between_live_ones(self):
        """A dataset can stay unarchived after its harvest flagged it `not-on-remote`."""
        resource_id = str(uuid4())
        stale = dataset([resource(resource_id)], last_update=datetime(2024, 9, 20))
        current = dataset([resource(resource_id)], last_update=datetime(2026, 8, 17))

        migrate()

        assert str(resources_of(current)[0].id) == resource_id
        assert str(resources_of(stale)[0].id) != resource_id

    def test_every_copy_archived_still_leaves_one_holder(self):
        resource_id = str(uuid4())
        older = dataset(
            [resource(resource_id)],
            archived=datetime(2022, 9, 28),
            last_update=datetime(2022, 9, 20),
        )
        newer = dataset(
            [resource(resource_id)],
            archived=datetime(2024, 9, 30),
            last_update=datetime(2024, 9, 20),
        )

        migrate()

        assert str(resources_of(newer)[0].id) == resource_id
        assert str(resources_of(older)[0].id) != resource_id

    def test_last_created_copy_wins_when_none_was_harvested(self):
        """Nothing else tells them apart, and the ids have to be resolved anyway."""
        resource_id = str(uuid4())
        older = dataset([resource(resource_id)])
        newer = dataset([resource(resource_id)])

        migrate()

        assert str(resources_of(newer)[0].id) == resource_id
        assert str(resources_of(older)[0].id) != resource_id

    def test_unharvested_duplicates_are_resolved_too(self):
        """An ambiguous id returns a 404 whatever produced it, so the deduplication is not
        restricted to harvested datasets. Their resources get no remote id: nothing on a
        remote ever designated them."""
        resource_id = str(uuid4())
        first = DatasetFactory(resources=[resource(resource_id, harvested=False)])
        second = DatasetFactory(resources=[resource(resource_id, harvested=False)])

        migrate()

        ids = {str(resources_of(first)[0].id), str(resources_of(second)[0].id)}
        assert len(ids) == 2
        assert resource_id in ids
        assert resources_of(first)[0].harvest is None
        assert resources_of(second)[0].harvest is None

    def test_rerunning_the_migration_changes_nothing(self):
        resource_id = str(uuid4())
        archived = dataset([resource(resource_id)], archived=datetime(2024, 9, 30))
        live = dataset([resource(resource_id)])

        migrate()
        after_first_run = {d.id: d.resources[0].to_mongo() for d in Dataset.objects}
        migrate()

        assert {d.id: d.resources[0].to_mongo() for d in Dataset.objects} == after_first_run
        assert str(resources_of(live)[0].id) == resource_id
        assert str(resources_of(archived)[0].id) != resource_id

    def test_unique_resources_are_left_alone(self):
        first, second = str(uuid4()), str(uuid4())
        dataset([resource(first)])
        dataset([resource(second)])

        migrate()

        assert {str(d.resources[0].id) for d in Dataset.objects} == {first, second}

    def test_the_same_id_in_several_datasets_is_resolved(self):
        """The shape the CKAN backend used to produce: one live dataset and its archived
        generations, all holding the same resource ids."""
        resource_id = str(uuid4())
        for _ in range(3):
            dataset([resource(resource_id)], archived=datetime(2024, 1, 1))
        live = dataset([resource(resource_id)])

        migrate()

        ids = [str(d.resources[0].id) for d in Dataset.objects]
        assert len(set(ids)) == 4
        assert str(resources_of(live)[0].id) == resource_id
