repos:

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
      - id: pip-compile
        name: pip-compile install.in
        args: [requirements/install.in, --output-file=requirements/install.pip]
        files: ^requirements/install\.(in|pip)$
      - id: pip-compile
        name: pip-compile test.in
        args: [requirements/test.in, --output-file=requirements/test.pip]
        files: ^requirements/(install|test)\.(in|pip)$
      - id: pip-compile
        name: pip-compile develop.in
        args: [requirements/develop.in, --output-file=requirements/develop.pip]
        files: ^requirements/(install|test|develop)\.(in|pip)$
      - id: pip-compile
        name: pip-compile doc.in
        args: [requirements/doc.in, --output-file=requirements/doc.pip]
        files: ^requirements/(install|doc)\.(in|pip)$
      - id: pip-compile
        name: pip-compile report.in
        args: [requirements/report.in, --output-file=requirements/report.pip]
        files: ^requirements/(install|test|report)\.(in|pip)$

  # https://github.com/pre-commit/pre-commit-hooks#pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1 # Ruff version
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --select, I]
      # Run the formatter
      - id: ruff-format
