name: udata_front Ui-Kit
match: '\.(js|cjs|vue|mjs|iced|liticed|coffee|litcoffee|ts|tsx|cs|ls|es6|es|jsx|sjs|co|eg|md|markdown|mdown|mkdn|mkd|mdwn|mkdown|ron|css|less|scss|sass)$'
theme:
  logo: theme/less/images/logo.png
  css:
    - theme/less/theme.css
  sidebar:
    background: "#b8e2ff"
    textColor: "#070d54"
excludeDir:
  - stylemark
examples:
  css:
    - udata_front/theme/gouvfr/static/less/index.css
    - theme/less/examples.css
  js:
    - udata_front/theme/gouvfr/static/js/index.js
