commit_message": '[ci skip]'
files:
  - source: /udata/translations/*.pot
    translation: /udata/translations/%two_letters_code%/LC_MESSAGES/udata.po
  - source: /js/locales/udata.en.json
    translation: /js/locales/udata.%two_letters_code%.json
