
from udata.core.dataset.models import Dataset


REASON_SPAM = 'spam'
REASON_PERSONAL_DATA = 'personal_data'
REASON_EXPLICIT_CONTENT = 'explicit_content'
REASON_ILLEGAL_CONTENT = 'illegal_content'
REASON_SECURITY = 'security'
REASON_OTHERS = 'others'
REPORT_REASONS_CHOICES = [
    REASON_SPAM,
    REASON_PERSONAL_DATA,
    REASON_EXPLICIT_CONTENT,
    REASON_ILLEGAL_CONTENT,
    REASON_SECURITY,
    REASON_OTHERS,
]

REPORTABLE_MODELS = [Dataset]