ACCESS_TYPE_OPEN = "open"
ACCESS_TYPE_OPEN_WITH_ACCOUNT = "open_with_account"
ACCESS_TYPE_RESTRICTED = "restricted"
ACCESS_TYPES = [
    ACCESS_TYPE_OPEN,
    ACCESS_TYPE_OPEN_WITH_ACCOUNT,
    ACCESS_TYPE_RESTRICTED,
]

ACCESS_AUDIENCE_ADMINISTRATION = "local_authority_and_administration"
ACCESS_AUDIENCE_COMPANY = "company_and_association"
ACCESS_AUDIENCE_PRIVATE = "private"

ACCESS_AUDIENCE_TYPES = [
    ACCESS_AUDIENCE_ADMINISTRATION,
    ACCESS_AUDIENCE_COMPANY,
    ACCESS_AUDIENCE_PRIVATE,
]

ACCESS_AUDIENCE_YES = "yes"
ACCESS_AUDIENCE_NO = "no"
ACCESS_AUDIENCE_UNDER_CONDITIONS = "under_condition"
ACCESS_AUDIENCE_CONDITIONS = [
    ACCESS_AUDIENCE_YES,
    ACCESS_AUDIENCE_NO,
    ACCESS_AUDIENCE_UNDER_CONDITIONS,
]

# INSPIRE Directive Article 13(1) limitation reason categories
INSPIRE_13_A_PUBLIC_AUTHORITIES = "confidentiality_of_proceedings_of_public_authorities"
INSPIRE_13_B_INTERNATIONAL_RELATIONS = "international_relations_public_security_or_national_defence"
INSPIRE_13_C_COURSE_OF_JUSTICE = "course_of_justice_or_fair_trial"
INSPIRE_13_D_COMMERCIAL_CONFIDENTIALITY = "confidentiality_of_commercial_or_industrial_information"
INSPIRE_13_E_INTELLECTUAL_PROPERTY = "intellectual_property_rights"
INSPIRE_13_F_PERSONAL_DATA = "confidentiality_of_personal_data"
INSPIRE_13_G_VOLUNTARY_SUPPLIER = "protection_of_voluntary_information_suppliers"
INSPIRE_13_H_ENVIRONMENTAL_PROTECTION = "protection_of_environment"

INSPIRE_LIMITATION_CATEGORIES = [
    INSPIRE_13_A_PUBLIC_AUTHORITIES,
    INSPIRE_13_B_INTERNATIONAL_RELATIONS,
    INSPIRE_13_C_COURSE_OF_JUSTICE,
    INSPIRE_13_D_COMMERCIAL_CONFIDENTIALITY,
    INSPIRE_13_E_INTELLECTUAL_PROPERTY,
    INSPIRE_13_F_PERSONAL_DATA,
    INSPIRE_13_G_VOLUNTARY_SUPPLIER,
    INSPIRE_13_H_ENVIRONMENTAL_PROTECTION,
]
