ACCESS_TYPE_OPEN = "open"
ACCESS_TYPE_OPEN_WITH_ACCOUNT = "open_with_account"
ACCESS_TYPE_RESTRICTED = "restricted"
ACCESS_TYPES = [
    ACCESS_TYPE_OPEN,
    ACCESS_TYPE_OPEN_WITH_ACCOUNT,
    ACCESS_TYPE_RESTRICTED,
]

ACCESS_AUDIENCE_ADMINISTRATION = "local_authority_and_administration"
ACCESS_AUDIENCE_COMPANY = "company_and_association"
ACCESS_AUDIENCE_PRIVATE = "private"

ACCESS_AUDIENCE_TYPES = [
    ACCESS_AUDIENCE_ADMINISTRATION,
    ACCESS_AUDIENCE_COMPANY,
    ACCESS_AUDIENCE_PRIVATE,
]

ACCESS_AUDIENCE_YES = "yes"
ACCESS_AUDIENCE_NO = "no"
ACCESS_AUDIENCE_UNDER_CONDITIONS = "under_condition"
ACCESS_AUDIENCE_CONDITIONS = [
    ACCESS_AUDIENCE_YES,
    ACCESS_AUDIENCE_NO,
    ACCESS_AUDIENCE_UNDER_CONDITIONS,
]
