DATASERVICE_FORMATS = ["REST", "WMS", "WSL"]


DATASERVICE_ACCESS_TYPE_OPEN = "open"
DATASERVICE_ACCESS_TYPE_OPEN_WITH_ACCOUNT = "open_with_account"
DATASERVICE_ACCESS_TYPE_RESTRICTED = "restricted"
DATASERVICE_ACCESS_TYPES = [
    DATASERVICE_ACCESS_TYPE_OPEN,
    DATASERVICE_ACCESS_TYPE_OPEN_WITH_ACCOUNT,
    DATASERVICE_ACCESS_TYPE_RESTRICTED,
]
