DATASERVICE_FORMATS = ["REST", "WMS", "WSL"]


DATASERVICE_ACCESS_TYPE_OPEN = "open"
DATASERVICE_ACCESS_TYPE_OPEN_WITH_ACCOUNT = "open_with_account"
DATASERVICE_ACCESS_TYPE_RESTRICTED = "restricted"
DATASERVICE_ACCESS_TYPES = [
    DATASERVICE_ACCESS_TYPE_OPEN,
    DATASERVICE_ACCESS_TYPE_OPEN_WITH_ACCOUNT,
    DATASERVICE_ACCESS_TYPE_RESTRICTED,
]

DATASERVICE_ACCESS_AUDIENCE_ADMINISTRATION = "local_authority_and_administration"
DATASERVICE_ACCESS_AUDIENCE_COMPANY = "company_and_association"
DATASERVICE_ACCESS_AUDIENCE_PRIVATE = "private"

DATASERVICE_ACCESS_AUDIENCE_TYPES = [
    DATASERVICE_ACCESS_AUDIENCE_ADMINISTRATION,
    DATASERVICE_ACCESS_AUDIENCE_COMPANY,
    DATASERVICE_ACCESS_AUDIENCE_PRIVATE,
]

DATASERVICE_ACCESS_AUDIENCE_YES = "yes"
DATASERVICE_ACCESS_AUDIENCE_NO = "no"
DATASERVICE_ACCESS_AUDIENCE_UNDER_CONDITIONS = "under_condition"
DATASERVICE_ACCESS_AUDIENCE_CONDITIONS = [
    DATASERVICE_ACCESS_AUDIENCE_YES,
    DATASERVICE_ACCESS_AUDIENCE_NO,
    DATASERVICE_ACCESS_AUDIENCE_UNDER_CONDITIONS,
]
